server:
  port: 8001
  servlet:
      context-path: /blog
spring:
  application:
    name: blog
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.151.48:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password:
mybatis:
  type-aliases-package: com.zuijianren.blog.pojo, com.zuijianren.blog.model
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: info
    com.zuijianren: debug
  file:
    name: log/blog.log


# 自定义项目参数
comment.avatar: /images/avatar.jpg