server:
  port: 80
spring:
  application:
    name: blog
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: '112233'
mybatis:
  type-aliases-package: com.zuijianren.blog.pojo, com.zuijianren.blog.model
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: info
    com.zuijianren: debug
  file:
    name: log/blog.log


# 自定义项目参数
comment.avatar: /images/avatar.jpg